spring:
  application:
    name: item
  data:
    mongodb:
      uri: mongodb://localhost:27017/itemdb
# Configuración para Mongo embebido (si usas Flapdoodle)
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.5
